name: Deploy
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pages: write
        steps:
          - name: Build docs
            uses: ./.github/actions/build-docs
            with:
              rspress-base: /${{ github.event.repository.name }}/

          - name: Deploy
            uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # tag v4.8.0
            with:
              folder: packages/tester/doc_build
              branch: gh-pages
              clean-exclude: pr-preview
              force: false